name: Continuous integration and deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ğŸ”§
        uses: viamrobotics/js-config/.github/actions/setup@main

      - name: Build ğŸ—ï¸
        run: pnpm run build

      - name: Lint and type check ğŸ’…
        run: pnpm run check

      - name: Run tests
        run: pnpm run test

      - name: Upload npm @viamrobotics/prime artifacts
        uses: actions/upload-artifact@v3
        with:
          name: npm-legacy-dist
          path: packages/legacy/dist

      - name: Upload npm @viamrobotics/prime-core artifacts
        uses: actions/upload-artifact@v3
        with:
          name: npm-core-dist
          path: packages/core/dist

      - name: Upload npm @viamrobotics/prime-blocks artifacts
        uses: actions/upload-artifact@v3
        with:
          name: npm-blocks-dist
          path: packages/blocks/dist

      - name: Upload GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: packages/storybook/prime

  deploy-npm:
    if: ${{ github.repository == 'viamrobotics/prime' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ğŸ”§
        uses: viamrobotics/js-config/.github/actions/setup@main
        with:
          registry-url: https://registry.npmjs.org
          node-version: "18"

      - name: Download @viamrobotics/prime npm artifacts
        uses: actions/download-artifact@v3
        with:
          name: npm-legacy-dist
          path: packages/legacy/dist

      - name: Download @viamrobotics/prime-core npm artifacts
        uses: actions/download-artifact@v3
        with:
          name: npm-core-dist
          path: packages/core/dist

      - name: Download @viamrobotics/prime-blocks npm artifacts
        uses: actions/download-artifact@v3
        with:
          name: npm-blocks-dist
          path: packages/blocks/dist

      - name: Publish ğŸš€
        run: pnpm publish -r --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-pages:
    if: ${{ github.repository == 'viamrobotics/prime' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
