name: Deploy Storybook / NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install ğŸ”§
        uses: ./.github/actions/setup

      - name: Build ğŸ—ï¸
        run: |
          npm run build-storybook
          npm run build
          touch ./prime/.nojekyll

      # TODO(mc, 2023-03-22): replace with GitHub-official action
      # https://github.com/actions/deploy-pages
      - name: Deploy Storybook ğŸš€
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: prime # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            .nojekyll

      - name: Publish ğŸš€
        uses: JS-DevTools/npm-publish@541aa6b21b4a1e9990c95a92c21adc16b35e9551
        with:
          token: ${{ secrets.NPM_TOKEN }}
